
MAIN_MENU = (
    '\nВарианты действий:'
    '\n1 - Погода в моем местоположении '
    '\n2 - Погода в городе '
    '\n3 - История запросов '
    '\n4 - Удаление всех запросов из истории '
    '\n5 - Выход'
)
OPTIONS = '\nВведите действие (1, 2, 3, 4, 5): '
ENTER_CITY = '\nВведите город: '
NUMBER_OF_REQUEST = '\nВведите сколько последних записей вывести: '
EXIT = '\nВыход из программы '
ALL_REMOVED = '\nВсе запросы из истории удалены '
PRINTED_ALL_REQUESTS = '\nВыведены все хранимые записи: '


SEPARATION_LINE = '\n------------------------------------------- '
CURRENT_TIME = '\nТекущее время: '
CITY_NAME = '\nНазвание города: '
WEATHER_CONDITIONS = '\nПогодные условия: '
TEMPERATURE = '\nТекущая температура: '
TEMPERATURE_FEELS_LIKE = '\nОщущается как: '
WIND_SPEED = '\nСкорость ветра: '
CELSIUS = ' градусов по цельсию'
MS = ' м/с'

RED_COLOR = '\033[91m'
RESET_COLOR = '\033[0m'

INCORRECT_MAIN_MENU_ENTRY = '\nНекорректный ввод, попробуйте ещё раз '
ValueError_TEXT = '\nНеобходимо вводить только целое число большее нуля, попробуйте ещё раз '
SaveStorageError_TEXT = '\nНе получилось сохранить данные '
OpenStorageError_TEXT = '\nНе получилось открыть файл истории запросов '
GeocoderError_TEXT = '\nОшибка при получении данных о вашем местоположении '
MissCityError_TEXT = '\nВведенный город не найден, попробуйте ещё раз '
ApiRequestError_TEXT = '\nПроблемы с получением ответа от сервера '
TypeError_TEXT = '\nОшибка с типом данных '
TypeMenuError_TEXT = '\nНекорректный ввод, попробуйте ещё раз '
LostConnectionError_TEXT = '\nОшибка соединения, попробуйте позже '
ExceptionError_TEXT = '\nНеизвестная ошибка, попробуйте позже '
TimeOutError_TEXT = '\nПревышено время ожидания от сервера, попробуйте позже '
DatabaseException_TEXT = '\nУ нас пролемы в работе с базами данных. Уже решаем их! '
NoStorageImplError_TEXT = '\nДанный тип хранилища не реализован в приложении '
EmptyStorageError_TEXT = '\nХранилище записей пустое '
